config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #ゲストユーザー用
  devise_scope :customer do
    post 'customers_guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    resources:pets, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources:posts, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
     #get 'posts/mypage'
     resource :favorites, only: [:create, :destroy]
     resources:comments, only:[:create, :destroy]
    end
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' => 'customers#update'
    get 'customers/mypage' => 'customers#show'
    #投稿履歴一覧画面
    get 'customers/mypost' => 'customers#mypost'
    #ペット登録履歴一覧画面
    get 'customers/mypet' => 'customers#mypet'
    #顧客の退会確認画面
    get 'customers/check'
    #顧客の退会処理(ステータスの更新)
    patch 'customers/withdraw'
  end
  #検索機能
  get "search" => "searches#search"

  namespace :admin do
    get '/' => 'homes#top'
    resources:customers, only:[:index, :show, :edit, :update]
    resources:posts, only:[:index, :destroy]
    resources:comments, only:[:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  #ログイン認証が成功していないと表示できない
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.page(params[:page]).per(20)
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:notice] = "削除に成功しました。"
    redirect_to admin_comments_path
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
    <div class="col-4 offset-1">
      <h2 class="py-5">
        <span>顧客コメント一覧</span>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2">
      <table class="table table-hover table-inverse mx-auto">
        <thead>
          <tr>
           <th>コメント</th>
          </tr>
        </thead>
        <tbody>
        <% @comments.each do |comment| %>
          <tr>
           <td>
            <%= comment.post.created_at.to_s(:datetime_jp) %> <%#to_sメソッドを呼び出して、引数にフォーマット名を指定 %>
            <div><%= comment.customer.name %></div>
           </td>
           <td class="pl-3">
            <%= comment.comment %>
           </td>
           <td class="pl-3">
            <%= link_to "削除", admin_comment_path(comment), method: :delete, class: "btn btn-danger", data:{ confirm: "本当に削除しますか？" } %>
           </td>
          </tr>
        <% end %>
         </tbody>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @comments %>
  </div>
</div>