config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #ゲストユーザー用
  devise_scope :customer do
    post 'customers_guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    resources:pets, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources:posts, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
     #get 'posts/mypage'
     resource :favorites, only: [:create, :destroy]
     resources:comments, only:[:create, :destroy]
    end
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' => 'customers#update'
    get 'customers/mypage' => 'customers#show'
    #投稿履歴一覧画面
    get 'customers/mypost' => 'customers#mypost'
    #ペット登録履歴一覧画面
    get 'customers/mypet' => 'customers#mypet'
    #顧客の退会確認画面
    get 'customers/check'
    #顧客の退会処理(ステータスの更新)
    patch 'customers/withdraw'
  end
  #検索機能
  get "search" => "searches#search"

  namespace :admin do
    get '/' => 'homes#top'
    resources:customers, only:[:index, :show, :edit, :update]
    resources:posts, only:[:index, :destroy]
    resources:comments, only:[:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #バリデーション
  validates :name, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約を設けています
  def active_for_authentication?
    super && (is_delete == false)
  end

  #ゲストのemailでデータベースから検索してあればレコードを使用なければパスワード、名前を追加して登録
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer| #そのメールアドレスが見つからなかったら
      customer.password = SecureRandom.urlsafe_base64 #ランダムに安全なパスワードを作るメッソド
      customer.name = "guest"
    end
  end

  #ゲストか判断する
  def guest?
    if self.email == 'guest@example.com'
      true
    else
      false
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  #ログイン認証が成功していないと表示できない
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(20)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = "変更を保存しました。"
    else
      render:edit
    end
  end

  private

  def customer_params
    #deviceの方に新規登録としてemailは、入っているが編集は入っていないのでいれる
    params.require(:customer).permit(:name, :is_delete, :email)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h2 class="py-5">
        <%= @customer.name %>さんの会員情報編集
      </h2>
    </div>
  </div>
  <%= render 'layouts/errors', obj: @customer %>

  <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <div class="row">
      <div class="col-8 offset-1">
        <table>
            <tr>
              <td class="pr-5 py-3">会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr class="field">
              <td class="pr-5 py-3">名前</td>
              <td class="pr-3"><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
              <td class="pr-5 py-3">メールアドレス</td>
              <td class="pr-3"><%= f.text_field :email, class: "form-control" %></td>
            </tr>
            <tr>
              <td class="pr-5 py-3">会員ステータス</td>
              <td>
                <%= f.radio_button :is_delete, :false %>
                <%= f.label :is_delete, "有効", value: false %>
                <%= f.radio_button :is_delete, :true  %>
                <%= f.label :is_delete, "退会", value: true %>
              </td>
            </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center mt-3">
    <%= f.submit '変更を保存', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-4 offset-1">
      <h2 class="py-5">
        <span>会員一覧</span>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2">
      <table class="table table-hover table-inverse mx-auto">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>名前</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_delete == false %>
                 <div style="color:limegreen;">有効</div>
                <% else %>
                 <div style="color:red;">退会</div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h2 class="py-5">
        <%= @customer.name %>さんの会員詳細
      </h2>
    </div>
  </div>

  <div class="row">
    <div class="col-8 offset-1">
      <table class="table">
        <tr>
          <td class="pr-5 py-2">会員ID</td>
          <td><%=@customer.id %></td>
        </tr>
        <tr>
          <td class="pr-5 py-2">名前</td>
          <td>
            <%= @customer.name %>
          </td>
        </tr>
        <tr>
          <td class="pr-5 py-2">メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td class="pr-5 py-2">会員ステータス</td>
          <td>
            <% if @customer.is_delete == false %>
              <div style="color:limegreen;">
                有効
              </div>
            <% else %>
              <div style="color:red;">
                退会
              </div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="py-4 col-5">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-success' %>
    </div>
  </div>
</div>