config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #ゲストユーザー用
  devise_scope :customer do
    post 'customers_guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    resources:pets, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources:posts, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
     #get 'posts/mypage'
     resource :favorites, only: [:create, :destroy]
     resources:comments, only:[:create, :destroy]
    end
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' => 'customers#update'
    get 'customers/mypage' => 'customers#show'
    #投稿履歴一覧画面
    get 'customers/mypost' => 'customers#mypost'
    #ペット登録履歴一覧画面
    get 'customers/mypet' => 'customers#mypet'
    #顧客の退会確認画面
    get 'customers/check'
    #顧客の退会処理(ステータスの更新)
    patch 'customers/withdraw'
  end
  #検索機能
  get "search" => "searches#search"

  namespace :admin do
    get '/' => 'homes#top'
    resources:customers, only:[:index, :show, :edit, :update]
    resources:posts, only:[:index, :destroy]
    resources:comments, only:[:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_customer!

  #検索モデル→params[:range]
  #検索方法→params[:search]
  #検索ワード→params[:word]

  def search
    @range = params[:range]

    if @range == "Pet"
      @pets = Pet.looks(params[:search], params[:word]).page(params[:page]).per(20)
    else
      @posts = Post.looks(params[:search], params[:word]).page(params[:page]).per(20)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class="col-8">
      <h2 class="py-5">検索結果</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-10 offset-1">
    <!--検索対象モデルがPetの時 -->
    <% if @range == "Pet" %>
      <% if @pets.blank? %>
        <h3 class="d-flex justify-content-center">見つかりませんでした。</h3>
      <% else %>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>ペット名</th>
              <th>動物の種類</th>
              <th>動物の品種</th>
              <th>性別</th>
              <th>体色</th>
              <th>生年月日</th>
            </tr>
          </thead>
          <tbody>
            <% @pets.each do |pet| %>
              <tr>
                <td><%= pet.pet_name %></td>
                <td><%= link_to  pet.pet_type, pet_path(pet.id) %></td>
                <td><%= pet.pet_kind %></td>
                <td><%= pet.gender_i18n %></td>
                <td><%= pet.color %></td>
                <td><%= pet.birth_date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      <div class="d-flex justify-content-center">
       <%= paginate @pets %>
      </div>
    <!--検索対象モデルがPetではない時(= 検索対象モデルがPostの時) -->
    <% elsif @range == "Post" %>
      <% if @posts.blank? %>
        <h3 class="d-flex justify-content-center">見つかりませんでした。</h3>
      <% else %>
        <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th>日付</th>
            <th>動物の種類</th>
            <th>体重</th>
            <th>フード種類</th>
            <th>フード量</th>
           </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.date %></td>
                <td><%= post.pet.pet_type %></td>
                <td><%= post.weight %></td>
                <td><%=  link_to post.feed, post_path(post.id) %></td>
                <td><%= post.amount_food %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
      <% end %>
    <div class="d-flex justify-content-center">
     <%= paginate @posts %>
    </div>
    <% end %>
</div>