config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #ゲストユーザー用
  devise_scope :customer do
    post 'customers_guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    resources:pets, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources:posts, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
     #get 'posts/mypage'
     resource :favorites, only: [:create, :destroy]
     resources:comments, only:[:create, :destroy]
    end
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' => 'customers#update'
    get 'customers/mypage' => 'customers#show'
    #投稿履歴一覧画面
    get 'customers/mypost' => 'customers#mypost'
    #ペット登録履歴一覧画面
    get 'customers/mypet' => 'customers#mypet'
    #顧客の退会確認画面
    get 'customers/check'
    #顧客の退会処理(ステータスの更新)
    patch 'customers/withdraw'
  end
  #検索機能
  get "search" => "searches#search"

  namespace :admin do
    get '/' => 'homes#top'
    resources:customers, only:[:index, :show, :edit, :update]
    resources:posts, only:[:index, :destroy]
    resources:comments, only:[:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         #devise.rbで全体的に名前でログインできるように設定したけど,
         #今回は管理者側はメールアドレスで設定したいので個別に書かないとダメ
         :database_authenticatable, authentication_keys: [:email]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  #バリデーション
  validates :name, presence: true

  # is_deletedがfalseならtrueを返すようにしている
  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約を設けています
  def active_for_authentication?
    super && (is_delete == false)
  end

  #ゲストのemailでデータベースから検索してあればレコードを使用なければパスワード、名前を追加して登録
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer| #そのメールアドレスが見つからなかったら
      customer.password = SecureRandom.urlsafe_base64 #ランダムに安全なパスワードを作るメッソド
      customer.name = "guest"
    end
  end

  #ゲストか判断する
  def guest?
    if self.email == 'guest@example.com'
      true
    else
      false
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :customer
  has_one_attached :image

  #バリデーション
  validates :image, presence: true, on: :create #新規登録の時だけバリデーションが反映される
  validates :pet_name, presence: true
  validates :pet_type, presence: true
  validates :pet_kind, presence: true
  validates :color, presence: true
  validates :personality, presence: true

  #動物の種類＋ペット名
  def select_type
    pet_type + ' ' + pet_name
  end

  #画像
   def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
   end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @pet = Pet.where("pet_type LIKE?", "#{word}")
    elsif search == "forward_match"
      @pet = Pet.where("pet_type LIKE?","#{word}%")
    elsif search == "backward_match"
      @pet = Pet.where("pet_type LIKE?","%#{word}")
    elsif search == "partial_match"
      @pet = Pet.where("pet_type LIKE?","%#{word}%")
    else
      @pet = Pet.all
    end
  end

  #enum の定義
  enum gender: { male: 0, female: 1, unknown: 2 }

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  belongs_to :pet
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #バリデーション
  validates :date, presence: true
  validates :weight, presence: true
  validates :feed, presence: true
  validates :amount_food, presence: true
  
  #いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("feed LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("feed LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("feed LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("feed LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  #ログイン認証が成功していないと表示できない
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.page(params[:page]).per(20)
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:notice] = "削除に成功しました。"
    redirect_to admin_comments_path
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  #ログイン認証が成功していないと表示できない
  before_action :authenticate_admin!

  def index
    @posts = Post.all.page(params[:page]).per(20)
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:notice] = "削除に成功しました。"
    redirect_to admin_posts_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  #ゲストユーザーを拒否
  def reject_guest_customer
    if current_customer.guest?
      redirect_to root_path
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_customer!

  #検索モデル→params[:range]
  #検索方法→params[:search]
  #検索ワード→params[:word]

  def search
    @range = params[:range]

    if @range == "Pet"
      @pets = Pet.looks(params[:search], params[:word]).page(params[:page]).per(20)
    else
      @posts = Post.looks(params[:search], params[:word]).page(params[:page]).per(20)
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight animal_weight.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header>
   <nav class="navbar navbar-expand-lg nav-color">
     <div class="container">
       <a class="navbar-brand" href="/"><%= image_tag ('Free_Sample_By_Wix.jpg') %></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                         aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>   <!--会員がログインしている場合-->
              <li style="color:white;" class="pt-2 pr-3"><span>ようこそ<%= current_customer.name %>さん！</span></li>
               <li>
                 <%= link_to customers_mypage_path, class: 'nav-link font-color' do %>
                   <i class="fas fa-user"></i> マイページ
                 <% end %>
               </li>
               <li>
                 <%= link_to posts_path, class: 'nav-link font-color' do %>
                   <i class="fas fa-list-ul"></i> 投稿一覧
                 <% end %>
               </li>
             <%#ゲストで入るとペット登録をしないように設定したので一緒にheaderのペット登録が見えないようにする %>
             <% if !current_customer.guest? %>
               <li>
                 <%= link_to new_pet_path, class: 'nav-link font-color' do %>
                   <i class="fas fa-paw"></i> ペット登録
                 <% end %>
               </li>
             <% end %>
               <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link font-color' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
               </li>
              <% elsif  admin_signed_in? %>  <!--管理者がログインしている場合-->
              <li>
                <%= link_to admin_customers_path, class: 'nav-link font-color' do %>
                  <i class="fas fa-user-circle"></i> 会員一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_posts_path, class: 'nav-link font-color' do %>
                 <i class="fas fa-list"></i> 投稿一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_comments_path, class: 'nav-link font-color' do %>
                  <i class="far fa-comments"></i> コメント一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link font-color' do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
              <% else %>  <!--ログインしていない状態-->
                <li>
                  <%= link_to homes_about_path, class: 'nav-link font-color' do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to customers_guest_sign_in_path, method: :post, class: 'nav-link font-color' do %>
                    <i class="fas fa-user"></i> ゲストログイン
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path, class: 'nav-link font-color' do %>
                    <i class="fas fa-user-plus"></i> 新規会員登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path, class: 'nav-link font-color' do %>
                    <i class="fas fa-sign-in-alt"></i> ログイン
                  <% end %>
                </li>
              <% end %>
              <%#検索窓%>
              <% if signed_in? %>
                <div class="search_form">
                  <%# 検索内容をwordとしてアクションに送る。%>
                  <%= form_with url: search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word, size: 10, placeholder: "動物,餌の種類を検索" %>
                    <%# 選択したモデルをrangeとしてアクションに送る %>
                    <%= f.select :range, options_for_select([['Pet'], ['Post']]) %>
                    <%# 選択した検索手法をsearchとしてアクションに送る %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn btn-primary btn-sm" %>
                  <% end %>
                </div>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalWeight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div style="color:limegreen;">
       <%= flash[:notice] %>
      </div>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>